avisalmon/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views
from matazim import views as matazim_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.home, name='home'),
    path('matazim/', include('matazim.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('main/', include('main.urls')),
    path('presenterz/', include('presenterz.urls')),
    path('accounts/signup/', main_views.signup, name="signup"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('randg/', include('randg.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('todo/', include('todo.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('profile/', views.my_profile_view, name='my_profile_view'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile/<int:profile_pk>',
         views.profile_view,
         name='profile'),
]

matazim/urls.py
from django.urls import path
from . import views

app_name='matazim'

urlpatterns = [
    path('', views.matazim_main, name='matazim_main'),
    path('program/', views.ProgramListView.as_view(),
         name='program_list'),
    path('program/create', views.ProgramCreateView.as_view(),
         name='program_create'),
    path('program/<int:pk>', views.ProgramDetailView.as_view(),
         name='program_detail'),
    path('program/update/<int:pk>', views.ProgramUpdateView.as_view(),
         name='program_update'),
    path('program/delete/<int:pk>', views.ProgramDeleteView.as_view(),
         name='program_delete'),
    path('program/add_member/<int:program_id>/<int:profile_id>',
         views.program_add_member,
         name='program_add_member'),
    path('program/remove_member/<int:program_id>/<int:profile_id>',
         views.program_remove_member,
         name='program_remove_member'),
]

matazim/models.py
from django.shortcuts import reverse
from django.db import models
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField
from main.models import Profile

class Program(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    description = models.TextField(max_length=5000, blank=True)
    link = models.URLField(max_length=200, blank=True)
    image = models.ImageField(upload_to='matazim/images/', blank=True)
    members = models.ManyToManyField(Profile, blank=True)

    def __str__(self):
        return self.name + ' (' + str(self.owner) + ')'

    def get_absolute_url(self):
        return reverse('matazim:program_detail', kwargs={'pk': self.pk})


class Facilitator(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    description = models.TextField(max_length=250, blank=True)
    link = models.URLField(max_length=200, blank=True)
    image = models.ImageField(upload_to='matazim/images/', blank=True)
    programs = models.ManyToManyField(Program, blank=True)
    members = models.ManyToManyField(Profile, blank=True)

    def __str__(self):
        return self.name


class Facility (models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    facilitator = models.ForeignKey(Facilitator, blank=True, on_delete=models.CASCADE)
    description = models.TextField(max_length=250, blank=True)
    link = models.URLField(max_length=200, blank=True)
    image = models.ImageField(upload_to='matazim/images/', blank=True)
    location = models.CharField(max_length=50, blank=True)
    members = models.ManyToManyField(Profile, blank=True)

    def __str__(self):
        return self.name

matazim/views.py
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .models import Program, Facilitator, Facility
from main.models import Profile


def matazim_main(request):
    return render(request, 'matazim/main_matazim.html')


class ProgramListView(ListView):
    model=Program


class ProgramDetailView(DetailView):
    model=Program


class ProgramCreateView(LoginRequiredMixin, CreateView):
    model=Program
    fields = ['name', 'description', 'link', 'image']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)


class ProgramUpdateView(LoginRequiredMixin, UpdateView):
    model=Program
    fields = ['name', 'description', 'link', 'image']

    def dispatch(self, request, *args, **kwargs):
        """" Making sure that only owners can update """
        obj = self.get_object()
        print(f'obj: {obj}')
        if obj.owner != self.request.user:
            print('Hi')
            return redirect('matazim:program_list')
        return super(ProgramUpdateView, self).dispatch(request, *args, **kwargs)


class ProgramDeleteView(DeleteView):
    model=Program
    success_url = reverse_lazy('matazim:program_list')


def program_add_member(request, program_id, profile_id):
    try:
        program = Program.objects.get(pk=program_id)
        profile = Profile.objects.get(pk=profile_id)
    except:
        return redirect('matazim:program_list')

    program.members.add(profile)
    return redirect('matazim:program_detail', pk=program_id)

def program_remove_member(request, program_id, profile_id):
    print(f'got here with {program_id} and {profile_id}')
    try:
        program = Program.objects.get(pk=program_id)
        profile = Profile.objects.get(pk=profile_id)
    except:
        return redirect('matazim:program_list')

    program.members.remove(profile)
    return redirect('matazim:program_detail', pk=program_id)

matazim/templates/matazim/main_matazim.html
{% extends "main/base_matazim.html" %}
{% load static %}

{% block content %}
  <h1>MATAZIM - מטצים </h1>
  <h3>This site will help us collect information about:</h3>
  <ul>
    <li>מטצים - מדריכים טכנולוגיים צעירים</li>
    <li>Technology Programs</li>
    <li>Facilitators (Schools, institutes etc.)</li>
    <li>Facilities (Maker spaces, innovation spaces...)</li>
    <li>Online training program</li>
  </ul>
  <h2>Get in - Sign up - be part of the game. </h2>
  <div class="jumbotron">
    <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{% static 'matazim/programs.jpg' %}" height=300 alt="">
    <div class="card-body">
      <h5 class="card-title">Programs</h5>
      <p class="card-text">Jump in and see all the different Education technical programs identified. Don’t see yours? Add it..</p>
      <a href={% url 'matazim:program_list' %} class="btn btn-primary">Go Programs</a>
    </div>
    <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{% static 'matazim/programs.jpg' %}" height=300 alt="">
    <div class="card-body">
      <h5 class="card-title">Programs</h5>
      <p class="card-text">Jump in and see all the different Education technical programs identified. Don’t see yours? Add it..</p>
      <a href={% url 'matazim:program_list' %} class="btn btn-primary">Go Programs</a>
    </div>
  </div>

</div>

{% endblock %}

matazim/templates/matazim/program_confirm_delete.html
{% extends "main/base_matazim.html" %}
{% load static %}

{% block content %}

{% if program.owner != user %}
<h1>You are not allowed to delete. It is not your Program! Go away. </h1>
<a href={% url 'matazim:program_list'  %}>Go back to Programs</a>
{% else %}

<form method="post">
{% csrf_token %}
<input type="hidden" name="program" value={{ program.pk }} >
<p>Are you sure you want to delete the Program: "{{ program }}"?</p>
<input type="submit" value="Confirm">
</form>

{% endif %}

{% endblock %}

matazim/templates/matazim/program_detail.html
{% extends "main/base_matazim.html" %}
{% load static %}
{% block content %}
<h1>{{ program.name}}</h1>

{% if user.profile in program.members.all %}
  <a href={% url 'matazim:program_remove_member' program.id user.profile.id %}>
  <button type="button" class="btn btn-danger">Remove me from this program</button>
  </a>
{% else %}
  <a href={% url 'matazim:program_add_member' program.id user.profile.id %}>
  <button type="button" class="btn btn-success">Add me as a member to this program</button>
  </a>
{% endif %}

{% if program.owner == user %}
<a href={% url 'matazim:program_update' program.id %}>
<button type="button" class="btn btn-success">Edit this Program</button>
</a>
<a href={% url 'matazim:program_delete' program.id %}>
<button type="button" class="btn btn-danger">Delete this Program</button>
</a>
{% endif %}
<a href={% url 'matazim:program_list' %}>
<button type="button" class="btn btn-success">Back to list</button>
</a>
<hr>

<p>owner:
  <a href={% url 'main:profile' program.owner.profile.id %}>
    ({{ program.owner}}): {{program.owner.first_name}} {{ program.owner.last_name }}
  </a>
</p>
<p>{{ program.description|safe }}</p>
{% if program.link %}
  <p><a href={{ program.link }} target="_blank">more info {{ program.link }}</a></p>
{% endif %}
{% if program.image %}
  <img src="{{ program.image.url }}" alt="" height=200>
{% endif %}

{% if program.members.count %}
<h2>Members:</h2>
<ul>
  {% for member in program.members.all %}
    <li>
      <a href={% url 'main:profile' member.id %} >
        ({{ member.user }}): {{member.user.first_name}} {{ member.user.last_name }}
      </a>
      {% if member == user.profile %}
      whoops, its me... <a href={% url 'matazim:program_remove_member' program.id member.id %}>get me out of here</a>
      {% endif %}
    </li>
  {% endfor %}
</ul>

{% else %}
  <h2>No members. </h2>
{% endif %}


{% endblock %}

matazim/templates/matazim/program_form.html
{% extends "main/base_matazim.html" %}
{% load static %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

matazim/templates/matazim/program_list.html
{% extends "main/base_matazim.html" %}

{% block content %}
<div class="container">
  <h1 dir="rtl">Educational Programs</h1>
  <h3>This is a list of educational programs</h3>
  <p>The focus is on programs that has technical orientation and can benifit using Matazim</p>
</div>
<hr>
<a href={% url 'matazim:program_create' %}>
<button type="button" class="btn btn-success">Add a new program you own</button>
</a>
<hr>
<ul>
  {% for program in program_list %}
    <li>
      <a href={% url 'matazim:program_detail' program.id %}>
        <p>{{ program.name }} ; owner: {{ program.owner.first_name}} {{ program.owner.last_name}}
      </a>
      {% if program.owner == user %}
      ... this is your program... <a href={% url 'matazim:program_delete' program.id %}>Remove it</a>
      {% endif %}
      </p>
    </li>
  {% endfor %}
</ul>


{% endblock %}