avisalmon/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views
from matazim import views as matazim_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.home, name='home'),
    path('matazim/', include('matazim.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('main/', include('main.urls')),
    path('presenterz/', include('presenterz.urls')),
    path('accounts/signup/', main_views.signup, name="signup"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('randg/', include('randg.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('todo/', include('todo.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('profile/', views.my_profile_view, name='my_profile_view'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile/<int:profile_pk>',
         views.profile_view,
         name='profile'),
]

todo/urls.py
from django.urls import path, re_path
from . import views

app_name='todo'

urlpatterns = [
    path('', views.todo_list_view, name='todo_list_view'),
    path('detail/<int:todo_pk>',
         views.todo_detail_view,
         name='todo_detail_view'),
    path('create/', views.todo_create_view, name='todo_create_view'),
    path('complete/<int:todo_pk>', views.completetodo, name='completetodo'),
    path('completedtodos/', views.completedtodos, name='completedtodos'),
    path('delete/<int:todo_pk>', views.deletetodo, name='deletetodo',)

]

todo/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class Todo(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'memo', 'important']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Todo
from .forms import TodoForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone


def todo_list_view(request):
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=True)
    context = {'todos':todos}
    return render(request, 'todo/todo_list_view.html', context)

@login_required
def todo_detail_view(request, todo_pk):
    todo = get_object_or_404(Todo,
                             pk=todo_pk,
                             user=request.user)
    if request.method=='GET':
        form = TodoForm(instance=todo)
        return render(request, 'todo/viewtodo.html', {'todo':todo, 'form':form})
    else:
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            return redirect('todo:todo_list_view')
        except ValueError:
            return render(request, 'todo/viewtodo.html', {'todo':todo, 'form':form, 'error':'Bad info'})

@login_required
def todo_create_view(request):
    if request.method == 'GET':
        return render(request, 'todo/createtodo.html', {'form':TodoForm()})
    else:
        try:
            form = TodoForm(request.POST)
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()
            return redirect('todo:todo_list_view')
        except ValueError:
            return render(request, 'todo/createtodo.html', {'form':TodoForm(), 'error':'Bad data passed in. Try again.'})


@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    #if request.method == 'POST':
    todo.datecompleted = timezone.now()
    todo.save()
    return redirect('todo:todo_list_view')

@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    todo.delete()
    return redirect('todo:todo_list_view')

@login_required
def completedtodos(request):
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=False).order_by('-datecompleted')
    return render(request, 'todo/completedtodos.html', {'todos':todos})

todo/templates/todo/completedtodos.html
{% extends "main/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <h1>Completed Todos</h1>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <div class="list-group">
                {% for todo in todos %}
                    <a href="{% url 'todo:todo_detail_view' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"><b>{{ todo.title }}</b> - Completed {{ todo.datecompleted|date:'M j Y H:i' }}</a>
                {% endfor %}
                <hr>
                <a href="{% url 'todo:todo_list_view' %}">Back to your Todo`s</a>
            </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/createtodo.html
{% extends "main/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Todo</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" class="form-control" id="title" required>
                </div>
                <div class="form-group">
                    <label for="memo">Memo</label>
                    <input name="memo" class="form-control" id="memo" ></input>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="important" class="form-check-input" id="important">
                    <label class="form-check-label" for="important">Important</label>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

todo/templates/todo/todo_list_view.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
  <h2>The ToDo project</h2>
  <p>This project example was implemented with function based views. see
  <a href="https://github.com/avisalmon/avisalmon" target="_blank">Githu</a>
  >All is implemented in the /todo app
  </p>
</div>

<div class="row justify-content-center mt-5">
    <div class="col-md-10">


        {% if todos %}
             <h1>{{ todos.count }} Current Todo{{ todos.count|pluralize }}</h1>
        {% else %}
                       <h1>Current Todos</h1>
        {% endif %}
        <a role="button" class="btn btn-primary" href="{% url 'todo:todo_create_view' %}">New Todo</a>
        <a role="button" class="btn btn-success" href="{% url 'todo:completedtodos' %}">Completed tasks</a>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-10">
    {% if todos %}
        <div class="list-group">
            {% for todo in todos %}
              <a href="{% url 'todo:todo_detail_view' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"><b>{{ todo.title }}</b>{% if todo.memo %} - {{ todo.memo|truncatechars:30 }}{% endif %}</a>
            {% endfor %}
        </div>
    {% else %}
        <div class="text-center">
            <h2>Looks like you don't have any todos! Nice work.</h2>
        <br>
        </div>
    {% endif %}
    </div>
</div>
{% endblock content %}

todo/templates/todo/viewtodo.html
{% extends "main/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Todo</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" class="form-control" id="title" value="{{ todo.title }}" required>
                </div>
                <div class="form-group">
                    <label for="memo">Memo</label>
                    <textarea name="memo" rows="5" class="form-control" id="memo" >{{ todo.memo }}</textarea>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="important" class="form-check-input" id="important" {% if todo.important %}checked{% endif %}>
                    <label class="form-check-label" for="important">Important</label>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                {% if todo.datecompleted is None %}
                <a class="btn btn-success" href="{% url 'todo:completetodo' todo.id %}">Complete</a>
                {% endif %}
                <a class="btn btn-danger" href="{% url 'todo:deletetodo' todo.id %}">Delete</a>
            </form>
        </div>

    </div>
    <div class="container">

    </div>

    {% if todo.datecompleted is not None %}
        <form style='display: none;' method="POST" action="{% url 'todo:completetodo' todo.id %}">
            {% csrf_token %}
            <button type="button" id="complete" type="submit">Complete</button>
        </form>
    {% endif %}
    <form style='display: none;' method="POST" action="{% url 'todo:deletetodo' todo.id %}">
        {% csrf_token %}
        <button id="delete" type="submit">Delete</button>
    </form>
    <p><a href="{% url 'todo:todo_list_view' %}"> Go back to all your Todo`s</a></p>
{% endblock %}