avisalmon/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views
from matazim import views as matazim_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.home, name='home'),
    path('matazim/', include('matazim.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('main/', include('main.urls')),
    path('presenterz/', include('presenterz.urls')),
    path('accounts/signup/', main_views.signup, name="signup"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('randg/', include('randg.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('todo/', include('todo.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('profile/', views.my_profile_view, name='my_profile_view'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile/<int:profile_pk>',
         views.profile_view,
         name='profile'),
]

matazim/urls.py
from django.urls import path
from . import views

app_name='matazim'

urlpatterns = [
    path('', views.matazim_main, name='matazim_main'),
    path('program/', views.ProgramListView.as_view(),
         name='program_list'),
    path('program/create', views.ProgramCreateView.as_view(),
         name='program_create'),
    path('program/<int:pk>', views.ProgramDetailView.as_view(),
         name='program_detail'),
    path('program/update/<int:pk>', views.ProgramUpdateView.as_view(),
         name='program_update'),
    path('program/delete/<int:pk>', views.ProgramDeleteView.as_view(),
         name='program_delete'),
    path('program/add_member/<int:program_id>/<int:profile_id>',
         views.program_add_member,
         name='program_add_member'),
    path('program/remove_member/<int:program_id>/<int:profile_id>',
         views.program_remove_member,
         name='program_remove_member'),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name='portfolio'

urlpatterns = [
    path('', views.portfolio, name='portfolio'),
    path('details/<int:project_id>',
         views.project_details,
         name='project_details'),
]

randg/urls.py
from django.urls import path
from . import views

app_name='randg'

urlpatterns = [
    path('', views.randg, name='randg'),
    path('generate/', views.generate, name='generate'),
]

todo/urls.py
from django.urls import path, re_path
from . import views

app_name='todo'

urlpatterns = [
    path('', views.todo_list_view, name='todo_list_view'),
    path('detail/<int:todo_pk>',
         views.todo_detail_view,
         name='todo_detail_view'),
    path('create/', views.todo_create_view, name='todo_create_view'),
    path('complete/<int:todo_pk>', views.completetodo, name='completetodo'),
    path('completedtodos/', views.completedtodos, name='completedtodos'),
    path('delete/<int:todo_pk>', views.deletetodo, name='deletetodo',)

]

main/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField

BIO_MAX_LENGTH = 12800
DESCRIPTION_MAX_LENGTH = 120
LONG_DESCRIPTION_MAX_LENGTH = 1024

PHONE_NUMBER_LENGTH = 15
MAX_EMAIL_LENGTH = 50
MAX_USERNAME_LENGTH = 40
MAX_URL_LENGTH = 256

FIELD_MAX_LENGTH = 50
FIELD_MAX_DIGITS = 10
FIELD_DECIMAL_PLACES = 8

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    bio = HTMLField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to='main/images/', blank=True, null=True)
    mataz = models.BooleanField(default=False)
    fake = models.BooleanField(default=False)

    def __str__(self):
        return f'Profile for {self.user}'

@receiver(post_save, sender=get_user_model())
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=get_user_model())
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class UserLink(models.Model):
    """A User contact info model"""
    provider = models.CharField(max_length=FIELD_MAX_LENGTH)
    display_name = models.TextField(max_length=MAX_USERNAME_LENGTH,
                                    null=True,
                                    blank=True)
    username = models.TextField(max_length=MAX_USERNAME_LENGTH,
                                null=True)
    user = models.ForeignKey(get_user_model(),
                             blank=True,
                             on_delete=models.CASCADE,
                             related_name='links')

    def __str__(self):
        return f'Link-{self.provider} for {self.user} as: ({self.username})'


# TODO: Might want to make some changes to the structure of this model.
class UserExperience(models.Model):
    """A User Experience Link model"""
    institution = models.CharField(max_length=FIELD_MAX_LENGTH,)
    experience = models.CharField(max_length=DESCRIPTION_MAX_LENGTH,
                                  blank=True,
                                  default='')
    experience_type = models.CharField(
        max_length=FIELD_MAX_LENGTH, default="work")
    # work, study, prize, project
    start_year = models.IntegerField(blank=True)
    finish_year = models.IntegerField(blank=True, null=True)
    description = models.CharField(max_length=LONG_DESCRIPTION_MAX_LENGTH,
                                   blank=True,
                                   null=True)
    user = models.ForeignKey(get_user_model(),
                             blank=True,
                             on_delete=models.CASCADE,
                             related_name='experiences')

    def __str__(self):
        return f'Expirience: {self.institution} for {self.user}'


class UserHobby(models.Model):
    """A User Hobby model"""
    title = models.CharField(max_length=FIELD_MAX_LENGTH,)
    description = models.CharField(max_length=BIO_MAX_LENGTH, blank=True)
    icon = models.CharField(max_length=FIELD_MAX_LENGTH, default="dice-d20")
    color = models.CharField(max_length=FIELD_MAX_LENGTH, default="#4169e1")

    user = models.ForeignKey(get_user_model(),
                             blank=True,
                             on_delete=models.CASCADE,
                             related_name='hobbies')

    def __str__(self):
        return f'Hobby: {self.title} for user: {self.user}'

main/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
#from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from tinymce.widgets import TinyMCE
from .models import Profile

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True,
                         label='Email',
                         error_messages={'exists': 'Such email exists in the system'})

    #bio = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))

    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "User Name"
        self.fields["email"].label = "Email address"

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

    def clean_email(self):
        if get_user_model().objects.filter(email=self.cleaned_data['email']).exists():
            raise ValidationError(self.fields['email'].error_messages['exists'])
        return self.cleaned_data['email']


class EditProfileForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ('email','first_name','last_name')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birth_date', 'image') #Note that we didn't mention user field here.

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
#from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.views.generic import (DetailView, UpdateView)
from .models import Profile
from .forms import EditProfileForm, ProfileForm


def home(request):
    return render(request, 'main/home.html')


def signup(request):
    if request.method == 'GET':
        return render(request, 'registration/signup.html', {'form':forms.UserCreateForm()})
    else:
        form = forms.UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            email = form.cleaned_data.get('email')
            authenticate( username=username,password=raw_password, backend='django.contrib.auth.backends.ModelBackend')
            user = get_user_model().objects.get(username=username)
            print(f'Login 0 - {user}')
            login(request, user)
            print('Login 1')
            return redirect('home')

        else:
            error = form.errors
            return render(request, 'registration/signup.html', {'form':forms.UserCreateForm(), 'error': error})

        # if request.POST['password1'] == request.POST['password2']:
        #     try:
        #         user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
        #         user.save()
        #         login(request, user)
        #         return redirect('home')
        #     except IntegrityError:
        #         return render(request,
        #                       'main/signuplocal.html',
        #                       {'form':UserCreationForm(),
        #                        'error':'That username has already been taken. Please choose a new username'})
        # else:
        #     return render(request, 'main/signup_local.html', {'form':UserCreationForm(), 'error':'Passwords did not match'})


@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    context = {
        'profile': profile
    }
    template = 'main/profile.html'
    return render(request, template, context)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)  # request.FILES is show the selected image or file
        print('Hi')
        if form.is_valid() and profile_form.is_valid():
            user_form = form.save()
            custom_form = profile_form.save(False)
            custom_form.user = user_form
            custom_form.save()
            return redirect('main:my_profile_view')
        else:
            context = {}
            context['form'] = EditProfileForm(instance=request.user)
            context['profile_form'] = ProfileForm(instance=request.user.profile)
            context['errors'] = 'You got errors. Try again'
            return render(request, 'main/edit_profile.html', context)

    else:
        form = EditProfileForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
        context = {}
        # args.update(csrf(request))
        context['form'] = form
        context['profile_form'] = profile_form
        return render(request, 'main/edit_profile.html', context)

def profile_view(request, profile_pk):
    profile = get_object_or_404(Profile, pk=profile_pk)
    context = {
        'profile': profile
    }
    template = 'main/profile_details.html'
    return render(request, template, context)

main/templates/main/base.html
<!doctype html>
{% load static %}
{% load socialaccount %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Acme&family=IBM+Plex+Serif:wght@300&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static "main/Logo.png" %}">
    <link rel="stylesheet" href={% static 'main/css/bootstrap.min.css' %}>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- The bellow is for tinymce editor cdn -->
    <!--  more info: https://www.codementor.io/hiteshgarg14/how-to-integrate-custom-rich-text-editor-in-django-54czmp0gi-->
    <script src="https://cdn.tiny.cloud/1/wqz74mr18ulmc97svb64752cmeadhyf5z3y7g3b556whx4m0/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({ selector:'textarea' });</script>

</head>
  <body>
    <!-- example navbar -->
    <div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-info text-white">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "main/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <!-- <span>Avi Home</span> -->
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">link1 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Django example pages
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="https://github.com/avisalmon/avisalmon">Site source on GitHub</a>
              <a class="dropdown-item" href="{% url 'randg:randg' %}">Password generator</a>
              <a class="dropdown-item" href="{% url 'portfolio:portfolio' %}">Personal Projects demo</a>
              <a class="dropdown-item" href="{% url 'todo:todo_list_view' %}">Todo Projects demo</a>
              <a class="dropdown-item" href="{% url 'presenterz:all_lectures' %}">PresenterZ</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Future link</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

  </div>

<div class="container">
      {% if user.is_authenticated %}
        <p>Looged in as <b>{{ user.username}} </b>  <a href="{% url 'logout' %}">Log out</a>
        <a href="{% url 'main:my_profile_view' %}">  |  See your profile</a>
      </p>
      {% else %}
        <p>
          <a href="{% url 'login' %}">Login</a>...
          <a href="{% url 'signup' %}">Sign Up</a>...
          <a href="{% provider_login_url 'github' %}">Login with GitHub</a>...
          <a href="{% provider_login_url 'google' %}">Login with Google</a>...
          <a href="{% provider_login_url 'facebook' %}">Login with FaceBook</a>...
        </p>
      {% endif %}
      {% block content %}{% endblock %}
</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/base_matazim.html
<!doctype html>
{% load static %}
{% load socialaccount %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Acme&family=IBM+Plex+Serif:wght@300&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static "main/Logo.png" %}">

    <link rel="stylesheet" href={% static 'main/css/bootstrap.min.css' %}>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- The bellow is for tinymce editor cdn -->
    <!--  more info: https://www.codementor.io/hiteshgarg14/how-to-integrate-custom-rich-text-editor-in-django-54czmp0gi-->
    <script src="https://cdn.tiny.cloud/1/wqz74mr18ulmc97svb64752cmeadhyf5z3y7g3b556whx4m0/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({ selector:'textarea' });</script>

</head>
  <body>
    <!-- example navbar -->
    <div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-primary text-white">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "main/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Matazim Logo">
        <!-- <span>Avi Home</span> -->
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Matazim<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
?             What do you want to see?
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <!-- <a class="dropdown-item" href=#>Learn</a> -->
              <a class="dropdown-item" href={% url 'matazim:program_list' %}>Programs</a>
              <a class="dropdown-item" href=#>Maker Spaces</a>
              <a class="dropdown-item" href=#>Events</a>
              <a class="dropdown-item" href=#>Teachers</a>
              <a class="dropdown-item" href=#>Matazim</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Connect us</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">in the news</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

  </div>

<div class="container">
      {% if user.is_authenticated %}
        <p>Looged in as ({{ user.username}}) <b>{{ user.first_name}} {{ user.last_name}}</b>  <a href="{% url 'logout' %}">Log out</a>
        <a href="{% url 'main:my_profile_view' %}">  |  See your profile</a>
      </p>
      {% else %}
        <p>
          <a href="{% url 'login' %}">Login</a>...
          <a href="{% url 'signup' %}">Sign Up</a>...
          <!-- <a href="{% provider_login_url 'github' %}">Login with GitHub</a>...
          <a href="{% provider_login_url 'google' %}">Login with Google</a>...
          <a href="{% provider_login_url 'facebook' %}">Login with FaceBook</a>...
        </p> -->
      {% endif %}
      {% block content %}{% endblock %}
</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/edit_profile.html
{% extends "main/base.html" %}

{% block content %}

<h1>Edit Your Profile</h1>

<p>User: {{ user }}</p>
<h2 style="color:red">{{ errors }}</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
  {{ form.as_p }}
  {{ profile_form }}
  </table>
  <button type="submit">Submit</button>
</form>

{% endblock %}

main/templates/main/home.html
{% extends "main/base.html" %}

{% block content %}

<h1>Welcome to my site</h1>
<p>A few projects are demonstrated here</p>
<p>Feel free to browse the menue</p>
<br>
<p>You can find this site on Githab. look for it up in the menu</p> 



{% endblock %}

main/templates/main/profile.html
{% extends "main/base.html" %}

{% block content %}

<h1>This is Your Profile page</h1>
<p><a href="{% url 'main:edit_profile' %}">Edit your profile</a></p>

<h2>{{ user.first_name }} {{ user.last_name }}</h2>
User: {{ user }}<br>
{% if user.profile.image %}
<img src="{{ user.profile.image.url }}" alt="" width=15% >
{% endif %}
<p><u><b>Bio:</b></u></p>
<p>  {{ user.profile.bio|safe }}</p>
<p><b>Birthday: </b>{{ user.profile.birth_date|date }}</p>
{% endblock %}

main/templates/main/profile_details.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

<h1>Profile page for {{ profile.user.first_name }} {{ profile.user.last_name}}</h1>
<i>User: {{ profile.user }}<br></i>
{% if profile.image %}
<img src="{{ profile.image.url }}" alt="" height=100 >
{% endif %}
{% if profile.bio %}
<p><u><b>Bio:</b></u></p>
<p>  {{ profile.bio|safe }}</p>
{% endif %}
{% if profile.birth_date %}
<p><b>Birthday: </b>{{ profile.birth_date|date }}</p>
{% endif %}
{% endblock %}

main/templates/main/signuplocal.html
{% extends "main/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'login' %}">Login here</a>
            </div>
        </div>
    </div>
{% endblock %}