avisalmon/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views
from matazim import views as matazim_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.home, name='home'),
    path('matazim/', include('matazim.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('main/', include('main.urls')),
    path('presenterz/', include('presenterz.urls')),
    path('accounts/signup/', main_views.signup, name="signup"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('randg/', include('randg.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('todo/', include('todo.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('profile/', views.my_profile_view, name='my_profile_view'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile/<int:profile_pk>',
         views.profile_view,
         name='profile'),
]

presenterz/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='presenterz'

urlpatterns = [
    path('',
         TemplateView.as_view(template_name='presenterz/presenterz.html'),
         name='presenterz'),
    path('all/', views.LectureListView.as_view(), name='all_lectures'),
    path('details/<int:pk>',
         views.LectureDetailView.as_view(),
         name='lecture_details'),
    path('create/', views.LectureCreateView.as_view(),
          name='lecture_create'),
    path('update/<int:pk>', views.LectureUpdateView.as_view(),
          name='lecture_update'),
    path('delete/<int:pk>', views.LectureDeleteView.as_view(),
          name='lecture_delete'),
    path('session/create/<int:lecture_pk>',
         views.SessionCreateView.as_view(),
         name='session_create'),
    path('session/<int:pk>',
         views.SessionDetailView.as_view(),
         name='session_details'),
    path('session/update/<int:pk>',
         views.SessionUpdateView.as_view(),
         name='session_update'),
    path('session/delete/<int:pk>',
         views.SessionDeleteView.as_view(),
         name='session_delete'),
    path('participation/create/<int:session_pk>',
         views.partcipationCreate,
         name='participation_create'),
    path('participation/delete/<int:session_pk>',
         views.paticipationDelete,
         name='participation_delete'),
]

presenterz/models.py
from django.db import models
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField
from django.utils import timezone
from django.shortcuts import reverse

class Lecture(models.Model):
    title = models.CharField(max_length=250)
    description = HTMLField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='presenterx/images/', blank=True)
    url = models.URLField(max_length=150, blank=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
            return self.title + ' by ' + str(self.user)


class Session(models.Model):
    lecture = models.ForeignKey(Lecture, related_name='sessions', on_delete=models.CASCADE)
    location = models.CharField(max_length = 30, default='Not specified')
    time = models.DateTimeField(default=timezone.now)
    length = models.IntegerField(default=60)
    link = models.URLField(max_length=200, blank=True)
    participants = models.ManyToManyField(get_user_model(), through='Participation')

    def __str__(self):
        return str(self.lecture) + ' - ' + self.location + ' - ' + str(self.time)

    def get_absolute_url(self):
        return reverse('presenterz:session_details', kwargs={'pk': self.pk})


class Participation(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)#(default=timezone.now)

    def __str__(self):
        return str(self.user) + ' --> ' + str(self.session)

    class Meta:
        unique_together = [['user', 'session']]

presenterz/forms.py
from django import forms
from .models import Session

# this file is not used. saving for history. 

class MyDateTimeInput(forms.DateTimeInput):
    input_type = "datetime-local" # <input type="datetime-local" ... />

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%dT%H:%M" # Output format (will be rendered as value="..." in HTML)
        super().__init__(**kwargs)

class SessionCreateForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = ['location', 'length', 'link']

    # time = forms.DateTimeField(
    #     input_formats=["%Y-%m-%dT%H:%M"], # How to parse the POST form data
    #     widget=MyDateTimeInput()
    # )

presenterz/views.py
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .models import Lecture, Session, Participation
from .forms import SessionCreateForm
import datetime
from django.db import IntegrityError

def presenterz(request):
    #todos = Todo.objects.filter(user=request.user, datecompleted__isnull=True)
    context = {}
    #context = {'todos':todos}
    return render(request, 'presenterz/presenterz.html', context)


class LectureListView(ListView):
    model = Lecture
    template_name = 'presenterz/all.html'
    context_object_name = 'all_lectures'

    def get_queryset(self):
        return Lecture.objects.order_by('-created')



class LectureDetailView(DetailView):
    model = Lecture

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sessions = Session.objects.filter(lecture_id=self.kwargs.get('pk'), time__gte=datetime.datetime.now()).order_by('time')
        context['sessions'] = sessions
        print(f'User is: {self.request.user}')
        listed_to_session = []
        for session in sessions:
            print(session)
            for participant in session.participants.all():
                print(f'Session: {session} / participant: {participant}')
                if participant == self.request.user:
                    listed_to_session.append(session.pk)
                    print(f'The user is listed to session {listed_to_session}')
        print(f'writing to context {listed_to_session}')
        context['listed_to_session'] = listed_to_session

        return context


class LectureCreateView(LoginRequiredMixin, CreateView):
    model = Lecture
    fields = ['title', 'description', 'image', 'url']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('presenterz:all_lectures')


class LectureUpdateView(LoginRequiredMixin, UpdateView):
    model = Lecture
    fields = ['title', 'description', 'image', 'url']

    def dispatch(self, request, *args, **kwargs):
        """" Making sure that only owners can update Lectires """
        obj = self.get_object()
        if obj.user != self.request.user:
            return redirect('presenterz:all_lectures')
        return super(LectureUpdateView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('presenterz:all_lectures')


class LectureDeleteView(LoginRequiredMixin, DeleteView):
    model = Lecture
    success_url = reverse_lazy('presenterz:all_lectures')


class SessionCreateView(LoginRequiredMixin, CreateView):
    model = Session
#    form_class = SessionCreateForm
    # don't apply lecture in the form - will be in thr kwargs
    # don;t show the time, it will be manualy handled in HTML
    #  and form_valid since I want to add datetime picker
    fields = ['location', 'length', 'link']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lecture'] = Lecture.objects.get(pk=self.kwargs.get('lecture_pk'))
        return context

    def form_valid(self, form):
        lecture = Lecture.objects.get(pk=self.kwargs.get('lecture_pk'))
        if lecture.user != self.request.user:
            return redirect('presenterz:lecture_details', pk=lecture.pk)
        form.instance.time = self.request.POST.get('time')
        form.instance.lecture = lecture
        return super().form_valid(form)


class SessionDetailView(DetailView):
    model=Session


class SessionUpdateView(LoginRequiredMixin, UpdateView):
    model = Session
    template_name = 'presenterz/session_update.html'
    fields = ['lecture', 'location', 'length', 'link']

    def form_valid(self, form):
        lecture = Lecture.objects.get(pk=self.request.POST.get('lecture'))
        if lecture.user != self.request.user:
            return redirect('presenterz:lecture_details', pk=lecture.pk)
        form.instance.time = self.request.POST.get('time')
        return super().form_valid(form)

class SessionDeleteView(LoginRequiredMixin, DeleteView):
    model=Session
    success_url = reverse_lazy('presenterz:all_lectures')

    def form_valid(self, form):
        lecture = Lecture.objects.get(pk=self.request.POST.get('lecture'))
        if lecture.user != self.request.user:
            return redirect('presenterz:lecture_details', pk=lecture.pk)
        form.instance.time = self.request.POST.get('time')
        return super().form_valid(form)

def partcipationCreate(request, session_pk):
    session = Session.objects.get(pk=session_pk)
    try:
        participation = Participation.objects.create(user=request.user, session=session)
    except IntegrityError:
        print('Validation error')
    return redirect('presenterz:lecture_details', session.lecture.pk)

def paticipationDelete(request, session_pk):
    session = Session.objects.get(pk=session_pk)

    user = request.user
    try:
        print('Suucesful delete should happen here')
        participation = Participation.objects.get(user=user, session=session)
        participation.delete()
        print(participation)
        return redirect('presenterz:lecture_details', session.lecture.pk)
    except:
        return redirect('presenterz:lecture_details', session.lecture.pk)

presenterz/templates/presenterz/all.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<h1>PRESENTERZ</h1>
<h2>Home site for the speakers community</h2>
<a href={% url 'presenterz:lecture_create' %}>
<button type="button" class="btn btn-success">New Lecture</button>
</a>
<div class="container">
  <div class="row">
    {% for lecture in all_lectures %}
    <div class="card col-md-4 border-primary">
      <a href={% url 'presenterz:lecture_details' lecture.pk %}>
      <h2><u><b>{{ lecture.title }}</b></u></h2><i> {{ lecture.created|date:"N Y" }}</i>
      </a>
      <p>{{ lecture.description|safe|truncatechars:150 }}
        <a href={% url 'presenterz:lecture_details' lecture.pk %}>...read more</a>
      </p>
      {% if lecture.url %}<p><a href={{ lecture.url }}>More info</a></p>{% endif %}
      <b><p>About the speaker:</p></b>
        <p>{{ lecture.user.first_name }} {{ lecture.user.last_name}}:
        <i>{{ lecture.user.profile.bio|safe|truncatechars:50}}
        <a href={% url 'main:profile' lecture.user.profile.pk %}>...read more about {{ lecture.user.first_name}}</a></i>
        </p>

    </div>

    {% endfor %}

  </div>

</div>

{% endblock %}

presenterz/templates/presenterz/lecture_confirm_delete.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

<form method="post">{% csrf_token %}
<p>Are you sure you want to delete the lecture: "{{ lecture }}"?</p>
<input type="submit" value="Confirm">
</form>

{% endblock %}

presenterz/templates/presenterz/lecture_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>Lecture: {{ lecture.title}}</h1>
      <a href={% url 'presenterz:all_lectures' %}>See all lectures  </a>
      {% if lecture.user == user %}
      <a href={% url 'presenterz:lecture_update' lecture.pk %}> / Edit</a>
      {% endif %}
      <a href={% url 'main:profile' lecture.user.profile.id %}>
      <p><i>{{ lecture.user.first_name }} {{ lecture.user.last_name }}</i></p>
      </a>
      <hr>
      <p>{{ lecture.description|safe }}</p>
      {% if lecture.image %}
      <img src="{{ lecture.image.url }}" alt="" height=200>
      {% endif %}
      {% if lecture.url %}
      <a href="{{ lecture.url }}">
      <p>More Info...</p>
      </a>
      {% endif %}
    </div>
    <div class="col">
      <h1>Coming lectures:</h1>

      <ul>
        {% for session in sessions %}
        {% if session.pk in listed_to_session %}
        <b><a href={% url 'presenterz:session_details' session.pk %}><li>{{ session.location }} - {{ session.time|date:"d N Y H:i"}}</li></a></b>
        <b><a href={% url 'presenterz:participation_delete' session.pk %}>You are listed to this session - sign out</a></b>
        {% else %}
        <a href={% url 'presenterz:session_details' session.pk %}><li>{{ session.location }} - {{ session.time|date:"d N Y H:i"}}</li></a>
        <a href={% url 'presenterz:participation_create' session.pk %}>Sign up to thie session</a>
        {% endif %}

        {% endfor %}

      </ul>

      {% if lecture.user == user %}
      <a href={% url 'presenterz:session_create' lecture_pk=lecture.pk %}>Add a new session</a>
      {% endif %}
    </div>

  </div>

</div>


{% endblock %}

presenterz/templates/presenterz/lecture_form.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

<h1>Create/update a new lecture</h1>
{% if lecture %}
<a href={% url 'presenterz:lecture_delete' lecture.pk  %}>Delete this lecture</a>
{% endif %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

presenterz/templates/presenterz/presenterz.html
{% extends "main/base.html" %}

{% block content %}

<h1>You are in the main presenters page. </h1>


{% endblock %}

presenterz/templates/presenterz/session_confirm_delete.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

{% if session.lecture.user != user %}
<h1>You are not allowed to delete. It is not your Lecture! Go away. </h1>
<a href={% url 'presenterz:lecture_details' session.lecture.pk %}>Go back to Lecture</a>
{% else %}

<form method="post">{% csrf_token %}
<input type="hidden" name="lectue" value={{ session.lecture.pk }} >
<p>Are you sure you want to delete the lecture: "{{ session }}"?</p>
<input type="submit" value="Confirm">
</form>

{% endif %}

{% endblock %}

presenterz/templates/presenterz/session_detail.html
{% extends "main/base.html" %}

{% block content %}
<h2>This is a session for lecture</h2>
<h1>{{ session.lecture.title }}</h1>
<h3><i>by
  {{ session.lecture.user.first_name }}
  {{ session.lecture.user.last_name }}</i></h3>
  <hr>
  {% if user == session.lecture.user %}
  <a class="btn btn-secondary" href={% url 'presenterz:session_update' session.pk %}>Edit  </a>
  <a class="btn btn-secondary" href={% url 'presenterz:session_delete' session.pk %}>Delete  </a>
  {% endif %}
  <a class="btn btn-secondary" href={% url 'presenterz:lecture_details' session.lecture.pk %}>Back to lecture</a></b>

<p>Place: {{ session.location }}</p>
 <p>Time: {{ session.time }}</p>
 <p>{{ session.length}} minutes</p>
 {% if session.link %}
 <p><a href={{ session.link }}>Link to registration</a></p>
 {% endif %}
 <hr>
 <h3>Who is coming? </h3>
 {% if not session.participants.all %}
 <p>No one is comming yet...</p>
 <p><a href={% url 'presenterz:participation_create' session.pk %}>Want to be the first to join? </a></p>
 {% else %}
 <ul>
   {% for participant in session.participants.all %}
  <li>{{ participant.first_name}} {{ participant.last_name }}</li>
   {% endfor %}
 </ul>
 <p><a href={% url 'presenterz:participation_create' session.pk %}>Want to join? </a></p>
 {% endif %}




{% endblock %}

presenterz/templates/presenterz/session_form.html
{% extends "main/base.html" %}

{% block content %}

<p>You are assigning a session for the Lecture: {{ lecture }}</p>
<form class=""  method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-group">
      <small id="" class="form-text text-muted">pick the date and time of your session</small>
      <label for="id_time">Time:</label>
      <input type="datetime-local" name="time" required id="id_time">
    </div>
    <input type="submit" value="Create New session">

</form>


{% endblock %}

presenterz/templates/presenterz/session_update.html
{% extends "main/base.html" %}

{% block content %}

<h1>You are editing the session for {{ session.lecture }}</h1>

  <form class="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="form-group">
    <small id="" class="form-text text-muted">pick the date and time of your session</small>
    <label for="id_time">Time:</label>
    <input type="datetime-local" name="time" value="{{ session.time|date:"Y-m-d\TH:i" }}" required id="id_time">
  </div>
  <!-- <p><label for="id_location">Location:</label>
  <input type="text" name="location" value={{ form.location }} maxlength="30" required id="id_location"></p>

  <p><label for="id_time">Time:</label>
  <input type="text" name="time" value={{ session.time|date:"Y-m-d\TH:i" }} required id="id_time"></p>

  <p><label for="id_length">Length:</label>
  <input type="number" name="length" value={{ session.length }} required id="id_length"></p>

  <p><label for="id_link">Link:</label>
  <input type="url" name="link" value={{ session.link }} maxlength="200" id="id_link"></p> -->

  <input type="submit" value="Update session">
  </form>

{% endblock %}